// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.


// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

var findTheDifference = function(s, t) {
    // sort letters and scan each to find difference
    
    // base case
    if(t.length === 1) return t[0];
    
    s = s.split('').sort();
    t = t.split('').sort();
    
    for(let i = 0; i < t.length; i++) {
        if(s[i] !== t[i]) {
            return t[i];
        }
    }
};

// sort letters and scan each to find difference
// Time: O(n log n) because of sorting
// Space: O(1)

var findTheDifference = function(s, t) {
    // hash maps
    
    // base case
    if(t.length === 1) return t[0];
    
    let map = {};
    
    // store longer string into map
    for(let letters of t) {
        map[letters] > 0 ? map[letters]++ : map[letters] = 1;
    }
    
    // loop through first string and subtract based on each character
    for(let i = 0; i < s.length; i++) {
        if(s[i] in map && map[s[i]] > 0) {
            map[s[i]]--;
        }
    }
    
    // the difference will be the character with 1 letter remaining
    for(let key in map) {
        if(map[key] > 0) {
            return key;
        }
    }
};

// Time: O(n)
// Space: O(n)